SELECT
    CAR_INDEX.CARPART,
    CAR_INDEX.CARMODEL,
    CAR_INDEX.CARNAME,
    CAR_INDEX.CARID,
    CAR_ITEM.HASTRAILER
        AS CAR_ITEM_NAME,
    CAR_INDEX.OTHER_NAME,
	CAR_INDEX.SIZE

FROM CAR_INDEX
LEFT JOIN CAR_ITEM
    ON CAR_INDEX.CARID = CAR_ITEM.CARID
