name: Pre-commit Checks

on: [push, pull_request]

jobs:
  pre-commit:
  runs-on: ubuntu-latest
steps:
  - name: Checkout code
uses: actions/checkout@v4

- name: Set up Python
uses: actions/setup-python@v5
with:
  python-version: '3.13.2'

- name: Install pre-commit
run: pip install pre-commit

#- name: Run pre-commit
#run: pre-commit run --all-files

- id:changed-files
  uses: tj-actions/changed-files@v46
  run: pre-commit run --show-diff-on-failure --color=always --files
