name: sql-check

on: 
  push:
    paths-ignore:
      - 'old/**'
  pull_request:
    paths-ignore:
      - 'old/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
    
      - name: Install pre-commit
        run: pip install pre-commit

      - name: Filter paths
        uses: dorny/paths-filter@v3
        id: filter
        with: 
          filters: |
            ignore:
              - '!old/**'
      - name: changed files
        uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files_ignore: |
           old/**
           .github/**

      - name: run pre-commit
        if: steps.filter.outputs.ignore == 'true'
        env: 
          all_changed_files = ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          pre-commit run --files ${all_changed_files}
          for file in ${all_changed_files}; do
            echo "pre-commit running on $file.."
          done
        shell: bash